pipeline:
  name: test-redis
  identifier: testredis
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: redis
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: make
                  identifier: make
                  spec:
                    shell: Sh
                    command: make REDIS_CFLAGS='-Werror' BUILD_TLS=yes
              - step:
                  type: Run
                  name: module api test
                  identifier: module_api_test
                  spec:
                    shell: Sh
                    command: ./runtest-moduleapi --verbose --dump-logs
              - step:
                  type: Run
                  name: test
                  identifier: test
                  spec:
                    shell: Sh
                    command: |-
                      sudo apt-get install tcl8.6 tclx
                      ./runtest --verbose --tags -slow --dump-logs
    - parallel:
        - stage:
            name: spell-check
            identifier: spellcheck
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: Install prerequisites
                      identifier: Install_prerequisites
                      spec:
                        shell: Sh
                        command: sudo pip install -r ./.codespell/requirements.txt
                  - step:
                      type: Run
                      name: Spell check
                      identifier: Spell_check
                      spec:
                        shell: Sh
                        command: codespell --config=./.codespell/.codespellrc
        - stage:
            name: build-centos7-jemalloc
            identifier: buildcentos7jemalloc
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        connectorRef: DhrubajyotiDocker
                        image: centos:7
                        shell: Sh
                        command: |-
                          yum -y install gcc make
                          make REDIS_CFLAGS='-Werror'
        - stage:
            name: build-libc-malloc
            identifier: buildlibcmalloc
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        shell: Sh
                        command: make REDIS_CFLAGS='-Werror' MALLOC=libc
        - stage:
            name: build-32bit
            identifier: build32bit
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        shell: Sh
                        command: |-
                          sudo apt-get update && sudo apt-get install libc6-dev-i386
                          make REDIS_CFLAGS='-Werror' 32bit
        - stage:
            name: build-macos-latest
            identifier: buildmacoslatest
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        shell: Sh
                        command: make REDIS_CFLAGS='-Werror'
        - stage:
            name: build-debian-old
            identifier: builddebianold
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        shell: Sh
                        command: |-
                          apt-get update && apt-get install -y build-essential
                          make REDIS_CFLAGS='-Werror'
        - stage:
            name: test-sanitizer-address
            identifier: testsanitizeraddress
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Cloud
                spec: {}
              execution:
                steps:
                  - step:
                      type: Run
                      name: make
                      identifier: make
                      spec:
                        shell: Sh
                        command: make SANITIZER=address REDIS_CFLAGS='-Werror' BUILD_TLS=module
                  - step:
                      type: Run
                      name: testprep
                      identifier: testprep
                      spec:
                        shell: Sh
                        command: sudo apt-get install tcl8.6 tclx -y
                  - step:
                      type: Run
                      name: test
                      identifier: test
                      spec:
                        shell: Sh
                        command: ./runtest --verbose --tags -slow --dump-logs
                  - step:
                      type: Run
                      name: module api test
                      identifier: module_api_test
                      spec:
                        shell: Sh
                        command: ./runtest-moduleapi --verbose --dump-logs
    - stage:
        name: external server
        identifier: external_server
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Build
                  identifier: Build
                  spec:
                    shell: Sh
                    command: make REDIS_CFLAGS=-Werror
              - step:
                  type: Run
                  name: Start redis-server
                  identifier: Start_redisserver
                  spec:
                    shell: Sh
                    command: |-
                      ./src/redis-server --daemonize yes --save "" --logfile external-redis.log \
                      --enable-protected-configs yes --enable-debug-command yes --enable-module-command yes
              - step:
                  type: Run
                  name: Run external test
                  identifier: Run_external_test
                  spec:
                    shell: Sh
                    command: |-
                      ./runtest \
                      --host 127.0.0.1 --port 6379 \
                      --tags -slow
  allowStageExecutions: true
