pipeline:
  name: test-redis
  identifier: testredis
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: redis
        build: <+input>
  stages:
    - stage:
        name: ci
        identifier: ci
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: make
                  identifier: make
                  spec:
                    shell: Sh
                    command: make REDIS_CFLAGS='-Werror' BUILD_TLS=yes
              - parallel:
                  - step:
                      type: Run
                      name: test
                      identifier: test
                      spec:
                        shell: Sh
                        command: |-
                          sudo apt-get install tcl8.6 tclx
                          ./runtest --verbose --tags -slow --dump-logs
                  - step:
                      type: Run
                      name: module api test
                      identifier: module_api_test
                      spec:
                        shell: Sh
                        command: ./runtest-moduleapi --verbose --dump-logs
